<?php

declare(strict_types=1);

namespace DSS\Entity\Signature;

final class SignatureLevel
{
	const XAdES_BASELINE_B = 'XAdES_BASELINE_B';
	
	const XAdES_BASELINE_T = 'XAdES_BASELINE_T';
	
	const XAdES_BASELINE_LT = 'XAdES_BASELINE_LT';
	
	const XAdES_BASELINE_LTA = 'XAdES_BASELINE_LTA';
	
	const CAdES_BASELINE_B = 'CAdES_BASELINE_B';
	
	const CAdES_BASELINE_T = 'CAdES_BASELINE_T';
	
	const CAdES_BASELINE_LT = 'CAdES_BASELINE_LT';
	
	const CAdES_BASELINE_LTA = 'CAdES_BASELINE_LTA';
	
	const JAdES_BASELINE_B = 'JAdES_BASELINE_B';
	
	const JAdES_BASELINE_T = 'JAdES_BASELINE_T';
	
	const JAdES_BASELINE_LT = 'JAdES_BASELINE_LT';
	
	const JAdES_BASELINE_LTA = 'JAdES_BASELINE_LTA';
	
	const PAdES_BASELINE_B = 'PAdES_BASELINE_B';
	
	const PAdES_BASELINE_T = 'PAdES_BASELINE_T';
	
	const PAdES_BASELINE_LT = 'PAdES_BASELINE_LT';
	
	const PAdES_BASELINE_LTA = 'PAdES_BASELINE_LTA';
}
